#!/bin/bash

BINDIR=`dirname $0`
cd $BINDIR

. ../etc/config


HOST=$1
USAGE="$0 - $HOST must not be empty !" 

if [[ "$HOST" == "" ]];then
 echo $USAGE
 exit 1
fi
echo yes|$telnet $HOST 22|$grep Connected	
exit $?
